# Generated by Django 5.0.2 on 2024-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10)),
                ('Student_name', models.CharField(max_length=30)),
                ('student_Email', models.CharField(max_length=30)),
                ('student_phone', models.PositiveIntegerField(max_length=10)),
                ('student_Address', models.CharField(max_length=30)),
            ],
        ),
    ]
